name: EXE Oluşturucu

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: EXE Derle
      run: |
        pyinstaller --noconfirm --onedir --windowed --add-data "templates;templates" app.py

    - name: EXE Dosyasını İndirilebilir Yap
      uses: actions/upload-artifact@v4
      with:
        name: OgrenciTakipSistemi-Windows-EXE
        path: dist/app/
